import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { generatedCodeLeakageDetector } from "../../src/detectors/generatedCodeLeakage.js";
import { runDetector } from "../helpers/runDetector.js";

describe("generated-code-leakage detector", () => {
  it("flags a production file importing from __generated__", async () => {
    const prod = `
import { UserFragment } from "./__generated__/graphql";

export function useUser() {
  return UserFragment;
}
`;
    const generated = `
export const UserFragment = {};
`;
    const issues = await runDetector(generatedCodeLeakageDetector, {
      "hooks/useUser.ts": prod,
      "hooks/__generated__/graphql.ts": generated,
    });

    assert.equal(issues.length, 1);
    assert.equal(issues[0]?.ruleId, "generated-code-leakage");
    assert.match(issues[0]?.message ?? "", /generated\/test path/);
  });

  it("flags a production file importing from __mocks__", async () => {
    const prod = `
import { mockDb } from "./__mocks__/database";

export const db = mockDb;
`;
    const mock = `
export const mockDb = { query: () => [] };
`;
    const issues = await runDetector(generatedCodeLeakageDetector, {
      "services/db.ts": prod,
      "services/__mocks__/database.ts": mock,
    });

    assert.equal(issues.length, 1);
    assert.match(issues[0]?.message ?? "", /__mocks__/);
  });

  it("flags a production file importing from __fixtures__", async () => {
    const prod = `
import { sampleOrder } from "../__fixtures__/orders";

export function getDefaultOrder() {
  return sampleOrder;
}
`;
    const fixture = `
export const sampleOrder = { id: "123", total: 100 };
`;
    const issues = await runDetector(generatedCodeLeakageDetector, {
      "services/orders.ts": prod,
      "__fixtures__/orders.ts": fixture,
    });

    assert.equal(issues.length, 1);
    assert.match(issues[0]?.message ?? "", /__fixtures__/);
  });

  it("flags a production file importing a .mock.ts file", async () => {
    const prod = `
import { fakeClient } from "./api.mock";

export const client = fakeClient;
`;
    const mock = `
export const fakeClient = { get: () => ({}) };
`;
    const issues = await runDetector(generatedCodeLeakageDetector, {
      "lib/client.ts": prod,
      "lib/api.mock.ts": mock,
    });

    assert.equal(issues.length, 1);
    assert.match(issues[0]?.message ?? "", /\.mock/);
  });

  it("flags a production file importing from fixtures/", async () => {
    const prod = `
import { seedData } from "../fixtures/seed";

export function init() {
  return seedData;
}
`;
    const fixture = `
export const seedData = [1, 2, 3];
`;
    const issues = await runDetector(generatedCodeLeakageDetector, {
      "src/init.ts": prod,
      "fixtures/seed.ts": fixture,
    });

    assert.equal(issues.length, 1);
  });

  it("flags a production file importing a file with @generated marker", async () => {
    const prod = `
import { schema } from "./schema";

export function getSchema() {
  return schema;
}
`;
    const generated = `
/** @generated by prisma — do not edit */
export const schema = {};
`;
    const issues = await runDetector(generatedCodeLeakageDetector, {
      "lib/getSchema.ts": prod,
      "lib/schema.ts": generated,
    });

    assert.equal(issues.length, 1);
    assert.match(issues[0]?.message ?? "", /@generated/);
    assert.equal(issues[0]?.confidence, 0.75);
  });

  it("does NOT flag test files importing from __fixtures__", async () => {
    const test = `
import { sampleOrder } from "../__fixtures__/orders";

describe("orders", () => {
  it("works", () => expect(sampleOrder).toBeDefined());
});
`;
    const fixture = `
export const sampleOrder = { id: "123" };
`;
    const issues = await runDetector(generatedCodeLeakageDetector, {
      "services/orders.test.ts": test,
      "__fixtures__/orders.ts": fixture,
    });

    assert.equal(issues.length, 0);
  });

  it("does NOT flag test files importing from __mocks__", async () => {
    const test = `
import { mockDb } from "./__mocks__/database";

test("db", () => {});
`;
    const mock = `
export const mockDb = {};
`;
    const issues = await runDetector(generatedCodeLeakageDetector, {
      "services/db.spec.ts": test,
      "services/__mocks__/database.ts": mock,
    });

    assert.equal(issues.length, 0);
  });

  it("does NOT flag files inside __tests__ importing from __fixtures__", async () => {
    const test = `
import { data } from "../__fixtures__/data";

test("it", () => {});
`;
    const fixture = `
export const data = {};
`;
    const issues = await runDetector(generatedCodeLeakageDetector, {
      "__tests__/integration.ts": test,
      "__fixtures__/data.ts": fixture,
    });

    assert.equal(issues.length, 0);
  });

  it("does NOT flag a production file importing from a normal module", async () => {
    const prod = `
import { helper } from "./utils";

export function main() {
  return helper();
}
`;
    const utils = `
export function helper() { return 42; }
`;
    const issues = await runDetector(generatedCodeLeakageDetector, {
      "src/main.ts": prod,
      "src/utils.ts": utils,
    });

    assert.equal(issues.length, 0);
  });

  it("does NOT flag non-relative (bare) imports", async () => {
    const prod = `
import React from "react";
import { z } from "zod";

export function App() { return null; }
`;
    const issues = await runDetector(generatedCodeLeakageDetector, {
      "App.tsx": prod,
    });

    assert.equal(issues.length, 0);
  });

  it("does NOT flag a production file importing a normal file without @generated", async () => {
    const prod = `
import { schema } from "./schema";

export function getSchema() {
  return schema;
}
`;
    const normal = `
export const schema = {};
`;
    const issues = await runDetector(generatedCodeLeakageDetector, {
      "lib/getSchema.ts": prod,
      "lib/schema.ts": normal,
    });

    assert.equal(issues.length, 0);
  });
});
