import type { DebtIssue, Detector, DetectorContext, Severity } from "../core/types.js";
import { createIssue } from "../utils/createIssue.js";

export interface TodoCommentPattern {
  regex: RegExp;
  severity: Severity;
  label: string;
}

export const defaultTodoCommentPatterns: TodoCommentPattern[] = [
  { regex: /\b(FIXME|BUG|BROKEN)\b/i, severity: "medium", label: "fixme/bug marker" },
  { regex: /\b(HACK|WORKAROUND|KLUDGE)\b/i, severity: "medium", label: "hack/workaround marker" },
  { regex: /\b(TODO|XXX)\b/i, severity: "low", label: "todo marker" },
  { regex: /\b(for now|temporary|temp|quick fix|placeholder|stub)\b/i, severity: "low", label: "temporary implementation marker" },
  { regex: /\b(generated by|ai generated|copilot|cursor|codex)\b/i, severity: "info", label: "assistant-generation marker" },
];

export function resolveTodoCommentPatterns(context: DetectorContext): TodoCommentPattern[] {
  const replaceDefaults = context.options.todoCommentReplaceDefaults === true;
  const disabled = new Set(context.options.todoCommentDisableDefaults ?? []);
  const patterns = replaceDefaults ? [] : defaultTodoCommentPatterns.filter((pattern) => !disabled.has(pattern.label));

  for (const marker of context.options.todoCommentMarkers ?? []) {
    patterns.push(marker);
  }

  return patterns;
}

export const todoCommentDetector: Detector = {
  id: "todo-comment",
  name: "Debt marker comment",
  description: "Finds comment markers that often identify debt accepted during fast implementation.",
  defaultSeverity: "low",
  tags: ["comments", "review", "cleanup"],
  detect(context: DetectorContext): DebtIssue[] {
    const issues: DebtIssue[] = [];
    const patterns = resolveTodoCommentPatterns(context);

    for (const file of context.files) {
      const lines = file.content.split(/\r?\n/);
      let countForFile = 0;
      for (let index = 0; index < lines.length; index += 1) {
        const line = lines[index] ?? "";
        if (!line.includes("//") && !line.includes("/*") && !line.includes("*")) continue;
        const match = patterns.find((pattern) => pattern.regex.test(line));
        if (!match) continue;

        issues.push(createIssue({
          detector: todoCommentDetector,
          severity: match.severity,
          confidence: 0.9,
          file: file.relativePath,
          location: { startLine: index + 1 },
          message: `Comment contains a ${match.label}.`,
          evidence: [line.trim().slice(0, 220)],
          suggestion: "Convert the marker into a tracked issue, add a removal condition, or fix it before more code depends on it.",
        }));

        countForFile += 1;
        if (countForFile >= 12) break;
      }
    }

    return issues;
  },
};

export function compileTodoCommentMarkers(
  markers: Array<{ pattern: string; severity?: Severity; label?: string }>,
): Array<{ regex: RegExp; severity: Severity; label: string }> {
  return markers.map((marker, index) => {
    let regex: RegExp;
    try {
      regex = new RegExp(marker.pattern, "i");
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw new Error(`Invalid todoComment.markers[${index}] pattern "${marker.pattern}": ${message}`);
    }

    return {
      regex,
      severity: marker.severity ?? "low",
      label: marker.label ?? `custom marker (${marker.pattern})`,
    };
  });
}
