import type { DebtLensConfig } from "../core/types.js";

export const defaultConfig: Required<Omit<DebtLensConfig, "pack" | "failOn" | "failOnConfidence" | "pluginApiVersion" | "plugins" | "ruleSeverities" | "ruleConfidenceFloors">> = {
  include: ["**/*.{ts,tsx,js,jsx}"],
  exclude: [
    "node_modules/**",
    "dist/**",
    "build/**",
    "coverage/**",
    ".next/**",
    ".expo/**",
    ".turbo/**",
    "ios/**",
    "android/**",
    "**/*.d.ts",
    "**/*.min.js",
    "**/*.test.{ts,tsx,js,jsx}",
    "**/*.spec.{ts,tsx,js,jsx}",
    "**/__tests__/**",
    "**/__mocks__/**"
  ],
  minSeverity: "low",
  rules: [],
  thresholds: {
    "large-component.maxLines": 250,
    "large-component.maxBranches": 16,
    "large-component.maxHooks": 10,
    "large-function.maxLines": 120,
    "large-function.maxBranches": 12,
    "state-sprawl.maxStatefulHooks": 6,
    "effect-complexity.maxLines": 30,
    "effect-complexity.maxDependencies": 8,
    "context-provider-sprawl.maxProviders": 4,
    "rn-host-forwarding.maxForwardedProps": 6,
    "rn-host-forwarding.maxHostTargets": 3,
    "route-handler-size.maxLines": 220,
    "route-handler-size.maxBranches": 14,
    "route-handler-size.maxAwaits": 6,
    "data-loader-sprawl.maxAwaits": 6,
    "data-loader-sprawl.maxFetches": 5,
    "data-loader-sprawl.maxBranches": 5,
    "data-loader-sprawl.maxLines": 90,
    "handler-depth.maxDepth": 4,
    "handler-depth.maxMiddleware": 5,
    "route-sprawl.maxRoutes": 8,
    "duplicate-logic.minSimilarity": 0.86,
    "duplicate-logic.minLines": 8,
    "duplicate-logic.maxSnippets": 450,
    "duplicated-literal.minLength": 6,
    "duplicated-literal.minCount": 3,
    "dead-abstraction.maxWrapperLines": 8,
    "prop-drilling.maxForwardedProps": 4,
    "naming-drift.minVariants": 5,
    "duplicate-logic.minStructuralSimilarity": 0.6,
    "barrel-file.maxReExports": 6,
    "weak-test-boundary.allowTypeOnly": 0,
    "api-surface-sprawl.maxExports": 12
  },
  maxFiles: 2000,
  respectGitignore: false,
  vocabulary: {},
  propDrilling: {
    ignoreComponents: [],
  },
  todoComment: {
    markers: [],
    replaceDefaults: false,
    disableDefaults: [],
  },
  namingDrift: {
    disableBuiltInVocabulary: false,
  },
};
